### PR TITLE
Fixed #217

### PR DESCRIPTION
**Pull request by jsilvestre**
I fixed your PR, and also changed a bit the existing comments to better match our new standard.

### CODE REVIEW

**Comment by sylzys** [comment]
Input is still desappearing on my brower :(

**Comment by jsilvestre** [comment]
Did you make sure you rebuild (restart brunch w) and clear the browser cache?

**Comment by sylzys** [comment]
yes :/

**Comment by jsilvestre** [comment]
Let me check.

**Comment by sylzys** [comment]
```
input.insertAfter @$('.badge')
```

is missing after l.103 in menu_item.coffee :)
Now it works

**Comment by jsilvestre** [comment]
https://github.com/sylzys/cozy-calendar/pull/1/files#diff-f0f11e8008c7a691318b6c0ab6332f02R109 ?

**Pull request merged**
